version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "samaggiPracticeRun"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-11cdodudfau59"
s3_prefix = "samaggiPracticeRun"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
